version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=asdf1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306